spring:
    application:
        name: zoo
    datasource:
        url: jdbc:postgresql://127.0.0.1:5433/zoo
        username: "postgres"
        password: "postgres"
        driver-class-name: org.postgresql.Driver

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        
